<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminHome.aspx.cs" Inherits="book_project.AdminHome" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>

    
<style>
    body {
  background: lightblue;
}
    .content {
   margin: auto;
  background: white;
  padding: 70px;
}

</style>
</head>
<body>
    <div class="content">
    <form id="form1" runat="server">
        <div>
        </div>
        USERS:&nbsp;&nbsp;
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="user_id" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" >
            <Columns>
                <asp:BoundField DataField="user_id" HeaderText="user_id" InsertVisible="False" ReadOnly="True" SortExpression="user_id" />
                <asp:BoundField DataField="user_name" HeaderText="user_name" SortExpression="user_name" />
                <asp:BoundField DataField="user_email" HeaderText="user_email" SortExpression="user_email" />
                <asp:BoundField DataField="user_password" HeaderText="user_password" SortExpression="user_password" />
                <asp:BoundField DataField="user_gender" HeaderText="user_gender" SortExpression="user_gender" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [User] WHERE [user_id] = @user_id" InsertCommand="INSERT INTO [User] ([user_name], [user_email], [user_password], [user_gender]) VALUES (@user_name, @user_email, @user_password, @user_gender)" SelectCommand="SELECT * FROM [User]" UpdateCommand="UPDATE [User] SET [user_name] = @user_name, [user_email] = @user_email, [user_password] = @user_password, [user_gender] = @user_gender WHERE [user_id] = @user_id">
            <DeleteParameters>
                <asp:Parameter Name="user_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="user_name" Type="String" />
                <asp:Parameter Name="user_email" Type="String" />
                <asp:Parameter Name="user_password" Type="String" />
                <asp:Parameter Name="user_gender" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="user_name" Type="String" />
                <asp:Parameter Name="user_email" Type="String" />
                <asp:Parameter Name="user_password" Type="String" />
                <asp:Parameter Name="user_gender" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <br />
        <br />
        <br />
        BOOKS:<br />
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="book_id" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource2">
            <Columns>
                <asp:BoundField DataField="book_id" HeaderText="book_id" InsertVisible="False" ReadOnly="True" SortExpression="book_id" />
                <asp:BoundField DataField="book_name" HeaderText="book_name" SortExpression="book_name" />
                <asp:BoundField DataField="author" HeaderText="author" SortExpression="author" />
                <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
                <asp:BoundField DataField="catagory" HeaderText="catagory" SortExpression="catagory" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Books] WHERE [book_id] = @book_id" InsertCommand="INSERT INTO [Books] ([book_name], [author], [price], [catagory]) VALUES (@book_name, @author, @price, @catagory)" SelectCommand="SELECT * FROM [Books]" UpdateCommand="UPDATE [Books] SET [book_name] = @book_name, [author] = @author, [price] = @price, [catagory] = @catagory WHERE [book_id] = @book_id">
            <DeleteParameters>
                <asp:Parameter Name="book_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="book_name" Type="String" />
                <asp:Parameter Name="author" Type="String" />
                <asp:Parameter Name="price" Type="String" />
                <asp:Parameter Name="catagory" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="book_name" Type="String" />
                <asp:Parameter Name="author" Type="String" />
                <asp:Parameter Name="price" Type="String" />
                <asp:Parameter Name="catagory" Type="String" />
                <asp:Parameter Name="book_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <asp:Button ID="Button4" runat="server" BackColor="#E6E6E6" Height="25px" OnClick="Button4_Click" Text="add books" Width="125px" />
        <br />
        <br />
        <br />
        ORDERS:<br />
        <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" DataKeyNames="order_Id" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource3" >
            <Columns>
                <asp:BoundField DataField="order_Id" HeaderText="order_Id" InsertVisible="False" ReadOnly="True" SortExpression="order_Id" />
                <asp:BoundField DataField="book_id" HeaderText="book_id" SortExpression="book_id" />
                <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Order] WHERE [order_Id] = @order_Id" InsertCommand="INSERT INTO [Order] ([book_id], [user_id]) VALUES (@book_id, @user_id)" SelectCommand="SELECT * FROM [Order]" UpdateCommand="UPDATE [Order] SET [book_id] = @book_id, [user_id] = @user_id WHERE [order_Id] = @order_Id">
            <DeleteParameters>
                <asp:Parameter Name="order_Id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="book_id" Type="Int32" />
                <asp:Parameter Name="user_id" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="book_id" Type="Int32" />
                <asp:Parameter Name="user_id" Type="Int32" />
                <asp:Parameter Name="order_Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>

        </div>
</body>
</html>
